version: '3.7'
services:
    app:
        build:
            context: .
    nginx:
        restart: always
        container_name: nginx-welding
        build: .
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:rw
        ports:
            - '80:80'
            - '443:443'
        networks:
            vlansrvnet:
                ipv4_address: 192.168.1.243
networks:
    vlansrvnet:
        external: true
        name: vlansrvnet
        driver: macvlan
        driver_opts:
            parent: enp1s0
        ipam:
            config:
                - subnet: '192.168.1.0/24'
                  ip_range: '192.168.1.192/27'
                  gateway: '192.168.1.254'
                  aux_addresses:
                      bridgehost: '192.168.1.251'
volumes:
    node_modules:
