version: '3.7'
services:
  app:
    build: .
    command: sh -c "npm run docker-start"
    ports:
      - 3200:4200
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
